// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: search_service.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cuisine       *string                `protobuf:"bytes,4,opt,name=cuisine,proto3,oneof" json:"cuisine,omitempty"`
	MaxPrepTime   *int32                 `protobuf:"varint,5,opt,name=max_prep_time,json=maxPrepTime,proto3,oneof" json:"max_prep_time,omitempty"`
	Difficulty    *string                `protobuf:"bytes,6,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Ingredients   []string               `protobuf:"bytes,7,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetCuisine() string {
	if x != nil && x.Cuisine != nil {
		return *x.Cuisine
	}
	return ""
}

func (x *SearchRequest) GetMaxPrepTime() int32 {
	if x != nil && x.MaxPrepTime != nil {
		return *x.MaxPrepTime
	}
	return 0
}

func (x *SearchRequest) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *SearchRequest) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *SearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RecipeResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*RecipeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type RecipeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cuisine       string                 `protobuf:"bytes,4,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	PrepTime      int32                  `protobuf:"varint,5,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	Difficulty    string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Rating        float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewsCount  int32                  `protobuf:"varint,9,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeResult) Reset() {
	*x = RecipeResult{}
	mi := &file_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResult) ProtoMessage() {}

func (x *RecipeResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RecipeResult) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *RecipeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecipeResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeResult) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

func (x *RecipeResult) GetPrepTime() int32 {
	if x != nil {
		return x.PrepTime
	}
	return 0
}

func (x *RecipeResult) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *RecipeResult) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecipeResult) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RecipeResult) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	mi := &file_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cuisine       string                 `protobuf:"bytes,4,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	PrepTime      int32                  `protobuf:"varint,5,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	Difficulty    string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Ingredients   []string               `protobuf:"bytes,7,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Instructions  string                 `protobuf:"bytes,9,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewsCount  int32                  `protobuf:"varint,11,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	AuthorId      string                 `protobuf:"bytes,12,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeResponse) Reset() {
	*x = RecipeResponse{}
	mi := &file_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResponse) ProtoMessage() {}

func (x *RecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RecipeResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *RecipeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecipeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeResponse) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

func (x *RecipeResponse) GetPrepTime() int32 {
	if x != nil {
		return x.PrepTime
	}
	return 0
}

func (x *RecipeResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *RecipeResponse) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *RecipeResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecipeResponse) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *RecipeResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RecipeResponse) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

func (x *RecipeResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type SuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
	mi := &file_search_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{5}
}

func (x *SuggestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SuggestionsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *SuggestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsResponse) Reset() {
	*x = SuggestionsResponse{}
	mi := &file_search_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsResponse) ProtoMessage() {}

func (x *SuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestionsResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SuggestionsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MeilisearchStatus string                 `protobuf:"bytes,4,opt,name=meilisearch_status,json=meilisearchStatus,proto3" json:"meilisearch_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_search_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetMeilisearchStatus() string {
	if x != nil {
		return x.MeilisearchStatus
	}
	return ""
}

var File_search_service_proto protoreflect.FileDescriptor

const file_search_service_proto_rawDesc = "" +
	"\n" +
	"\x12search_service.proto\x12\x06search\x1a\x1bgoogle/protobuf/empty.proto\"\xb5\x01\n" +
	"\x0fSearchRequest\x12\r\n" +
	"\x05query\x18\x01 \x01(\t\x12\x0c\n" +
	"\x04page\x18\x02 \x01(\x05\x12\x11\n" +
	"\apage_size\x18\x03 \x01(\x05\x12\x18\n" +
	"\acuisine\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x1b\n" +
	"\rmax_prep_time\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x22\n" +
	"\fingredients\x18\a \x03(\t\x12\x14\n" +
	"\x04tags\x18\b \x03(\tB\t\n" +
	"\a_cuisineB\x10\n" +
	"\x0e_max_prep_timeB\r\n" +
	"\v_difficulty\"y\n" +
	"\x0eSearchResponse\x12\x1e\n" +
	"\aroots\x18\x01 \x03(\v2\x0e.search.RecipeResult\x12\r\n" +
	"\x05total\x18\x02 \x01(\x05\x12\x0c\n" +
	"\x04page\x18\x03 \x01(\x05\x12\x11\n" +
	"\apage_size\x18\x04 \x01(\x05\x12\x13\n" +
	"\vtotal_pages\x18\x05 \x01(\x05\"|\n" +
	"\x0cRecipeResult\x12\n" +
	"\n" +
	"\x02id\x18\x01 \x01(\t\x12\r\n" +
	"\x05title\x18\x02 \x01(\t\x12\x22\n" +
	"\vdescription\x18\x03 \x01(\t\x12\x18\n" +
	"\acuisine\x18\x04 \x01(\t\x12\x1b\n" +
	"\aprep_time\x18\x05 \x01(\x05\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\t\x12\x14\n" +
	"\x04tags\x18\a \x03(\t\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01\x12\x17\n" +
	"\rviews_count\x18\t \x01(\x05\"#\n" +
	"\x11GetRecipeRequest\x12\n" +
	"\n" +
	"\x02id\x18\x01 \x01(\t\"\xd6\x01\n" +
	"\x0fRecipeResponse\x12\n" +
	"\n" +
	"\x02id\x18\x01 \x01(\t\x12\r\n" +
	"\x05title\x18\x02 \x01(\t\x12\x22\n" +
	"\vdescription\x18\x03 \x01(\t\x12\x18\n" +
	"\acuisine\x18\x04 \x01(\t\x12\x1b\n" +
	"\aprep_time\x18\x05 \x01(\x05\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\t\x12\x22\n" +
	"\fingredients\x18\a \x03(\t\x12\x14\n" +
	"\x04tags\x18\b \x03(\t\x12\x22\n" +
	"\x0finstructions\x18\t \x01(\t\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01\x12\x17\n" +
	"\rviews_count\x18\v \x01(\x05\x12\x1b\n" +
	"\aauthor_id\x18\f \x01(\t\"\x65\n" +
	"\x12SuggestionsRequest\x12\r\n" +
	"\x05query\x18\x01 \x01(\t\x12\x16\n" +
	"\x04type\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n" +
	"\x05limit\x18\x03 \x01(\x05B\a\n" +
	"\x05_type\"Y\n" +
	"\x13SuggestionsResponse\x12\x22\n" +
	"\fsuggestions\x18\x01 \x03(\t\x12\x0c\n" +
	"\x04type\x18\x02 \x01(\t\"\x9a\x01\n" +
	"\x0fHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\t\x12\x18\n" +
	"\aversion\x18\x02 \x01(\t\x12\x18\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03\x12#\n" +
	"\x12meilisearch_status\x18\x04 \x01(\t2\x9e\x02\n" +
	"\x0fSearchService\x12<\n" +
	"\rSearchRecipes\x12\x17.search.SearchRequest\x1a\x16.search.SearchResponse\x12;\n" +
	"\aGetRecipe\x12\x19.search.GetRecipeRequest\x1a\x17.search.RecipeResponse\x12I\n" +
	"\x0eGetSuggestions\x12\x1a.search.SuggestionsRequest\x1a\x1b.search.SuggestionsResponse\x12;\n" +
	"\x05Health\x12\x16.google.protobuf.Empty\x1a\x17.search.HealthResponseBXZ?github.com/lamauspex/recipes/backend/shared/proto\xaa\x02\x06Searchb\x06proto3"

var (
	file_search_service_proto_rawDescOnce sync.Once
	file_search_service_proto_rawDescData []byte
)

func file_search_service_proto_rawDescGZIP() []byte {
	file_search_service_proto_rawDescOnce.Do(func() {
		file_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)))
	})
	return file_search_service_proto_rawDescData
}

var file_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)

func file_search_service_proto_goTypes() []any {
	return []any{
		(*SearchRequest)(nil),
		(*SearchResponse)(nil),
		(*RecipeResult)(nil),
		(*GetRecipeRequest)(nil),
		(*RecipeResponse)(nil),
		(*SuggestionsRequest)(nil),
		(*SuggestionsResponse)(nil),
		(*HealthResponse)(nil),
	}
}

var file_search_service_proto_depIdxs = []int32{
	2, // 0: search.SearchResponse.results:type_name -> search.RecipeResult
	1, // 1: search.SearchService.SearchRecipes:input -> search.SearchRequest
	2, // 2: search.SearchService.SearchRecipes:output -> search.SearchResponse
	3, // 3: search.SearchService.GetRecipe:input -> search.GetRecipeRequest
	4, // 4: search.SearchService.GetRecipe:output -> search.RecipeResponse
	5, // 5: search.SearchService.GetSuggestions:input -> search.SuggestionsRequest
	6, // 6: search.SearchService.GetSuggestions:output -> search.SuggestionsResponse
	7, // 7: search.SearchService.Health:input -> google.protobuf.Empty
	7, // 8: search.SearchService.Health:output -> search.HealthResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() {
	file_search_service_proto_init()
}

func file_search_service_proto_init() {
	if File_search_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_service_proto_goTypes(),
		DependencyIndexes: file_search_service_proto_depIdxs,
		MessageInfos:      file_search_service_proto_msgTypes,
	}.Build()
	File_search_service_proto = out.File
	// file_search_service_proto_goTypes = nil  // Cleared after init
	// file_search_service_proto_depIdxs = nil  // Cleared after init
}
