"""create new table

Revision ID: 139ee91289cb
Revises: 
Create Date: 2026-04-29 17:58:35.950495

"""
from alembic import op
import sqlalchemy as sa

from backend.shared.models.base.decorator.type_decorator import (
    UUIDTypeDecorator)

# revision identifiers, used by Alembic.
revision = '139ee91289cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
                    sa.Column('user_id', UUIDTypeDecorator(),
                              nullable=False,
                              comment='ID пользователя'),
                    sa.Column('name_recipe',
                              sa.String(length=150),
                              nullable=False,
                              comment='Название рецепта'),
                    sa.Column('description',
                              sa.String(length=500),
                              nullable=False,
                              comment='Описание рецепта'),
                    sa.Column('id', UUIDTypeDecorator(),
                              nullable=False,
                              comment='Уникальный идентификатор'),
                    sa.Column('created_at',
                              sa.DateTime(timezone=True),
                              server_default=sa.text("timezone('utc', now())"),
                              nullable=False,
                              comment='Время создания записи'),
                    sa.Column('updated_at',
                              sa.DateTime(timezone=True),
                              server_default=sa.text("timezone('utc', now())"),
                              nullable=True,
                              comment='Время последнего обновления'),
                    sa.Column('is_active',
                              sa.Boolean(),
                              nullable=False,
                              comment='Флаг активности записи'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recipes_id'),
                    'recipes',
                    ['id'],
                    unique=False)
    op.create_index(op.f('ix_recipes_user_id'),
                    'recipes',
                    ['user_id'],
                    unique=False)
    op.create_table('ingredients',
                    sa.Column('recipe_id', UUIDTypeDecorator(),
                              nullable=False,
                              comment='ID рецепта'),
                    sa.Column('ingredient',
                              sa.String(length=50),
                              nullable=False,
                              comment='Ингредиенты'),
                    sa.Column('quantity',
                              sa.String(length=50),
                              nullable=False,
                              comment='Количество'),
                    sa.Column('unit',
                              sa.String(length=50),
                              nullable=False,
                              comment='Единица измерения'),
                    sa.Column('id', UUIDTypeDecorator(),
                              nullable=False,
                              comment='Уникальный идентификатор'),
                    sa.Column('created_at',
                              sa.DateTime(timezone=True),
                              server_default=sa.text(
                                  "timezone('utc', now())"),
                              nullable=False,
                              comment='Время создания записи'),
                    sa.Column('updated_at',
                              sa.DateTime(timezone=True),
                              server_default=sa.text(
                                  "timezone('utc', now())"),
                              nullable=True, comment='Время последнего обновления'),
                    sa.Column('is_active', sa.Boolean(), nullable=False,
                              comment='Флаг активности записи'),
                    sa.ForeignKeyConstraint(
                        ['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ingredients_id'),
                    'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_recipe_id'),
                    'ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_recipe_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
