
name: r_m_project

include:
  - volumes.yaml
  - services/service_user.yaml
  - services/service_recipe.yaml
  - services/service_search.yaml
  - database/postgres_user.yaml
  - database/postgres_recipe.yaml
  - database/rabbitmq.yaml
  - database/meilisearch.yaml

networks:
  recipe_network:
    driver: bridge

