# ==========================================
# Docker Volumes
# ==========================================
# Определение всех томов для проекта
# Используется для сохранения данных 
# между перезапусками контейнеров

volumes:
  # ==========================================
  # PostgreSQL User Service
  # ==========================================
  postgres_user_data:
    driver: local


  # ==========================================
  # PostgreSQL Recipe Service
  # ==========================================
  postgres_recipe_data:
    driver: local


  # ==========================================
  # RabbitMQ
  # ==========================================
  rabbitmq_data:
    driver: local


  # ==========================================
  # Meilisearch
  # ==========================================
  meilisearch_data:
    driver: local

