"""create new table

Revision ID: 10e56fa32c1e
Revises: 001
Create Date: 2026-03-29 15:10:22.776638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10e56fa32c1e'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loginattempts', 'user_id',
                    existing_type=sa.UUID(),
                    comment='ID пользователя (если пользователь существует)',
                    existing_nullable=True)
    op.alter_column('loginattempts', 'email',
                    existing_type=sa.VARCHAR(length=100),
                    comment='Email, с которого была попытка входа',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'ip_address',
                    existing_type=sa.VARCHAR(length=45),
                    comment='IP адрес, с которого была попытка',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'user_agent',
                    existing_type=sa.VARCHAR(length=500),
                    comment='User Agent браузера',
                    existing_nullable=True)
    op.alter_column('loginattempts', 'is_successful',
                    existing_type=sa.BOOLEAN(),
                    comment='Успешна ли попытка входа',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'failure_reason',
                    existing_type=sa.VARCHAR(length=100),
                    comment='Причина неудачи',
                    existing_nullable=True)
    op.alter_column('loginattempts', 'id',
                    existing_type=sa.UUID(),
                    comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('loginattempts', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    comment='Время последнего обновления')
    op.alter_column('loginattempts', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_loginattempts_user_id'),
                    'loginattempts', ['user_id'], unique=False)
    op.alter_column('refreshtokens', 'user_id',
                    existing_type=sa.UUID(),
                    comment='ID пользователя',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'token',
                    existing_type=sa.VARCHAR(length=255),
                    comment='Значение токена',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'is_revoked',
                    existing_type=sa.BOOLEAN(),
                    comment='Флаг отзыва токена',
                    existing_nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('refreshtokens', 'expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время истечения',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'id',
                    existing_type=sa.UUID(),
                    comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('refreshtokens', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    comment='Время последнего обновления')
    op.alter_column('refreshtokens', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.drop_constraint('refreshtokens_token_key',
                       'refreshtokens', type_='unique')
    op.create_index(op.f('ix_refreshtokens_token'),
                    'refreshtokens', ['token'], unique=True)
    op.alter_column('users', 'user_name',
                    existing_type=sa.VARCHAR(length=50),
                    comment='Имя пользователя',
                    existing_nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=100),
                    comment='Email пользователя',
                    existing_nullable=False)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    comment='Хешированный пароль',
                    existing_nullable=False)
    op.alter_column('users', 'full_name',
                    existing_type=sa.VARCHAR(length=100),
                    comment='Полное имя',
                    existing_nullable=True)
    op.alter_column('users', 'bio',
                    existing_type=sa.TEXT(),
                    comment='Биография пользователя',
                    existing_nullable=True)
    op.alter_column('users', 'email_verified',
                    existing_type=sa.BOOLEAN(),
                    comment='Подтвержден ли email',
                    existing_nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('users', 'verification_token',
                    existing_type=sa.VARCHAR(length=255),
                    comment='Токен для подтверждения email',
                    existing_nullable=True)
    op.alter_column('users', 'verification_expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время истечения токена верификации',
                    existing_nullable=True)
    op.alter_column('users', 'password_reset_token',
                    existing_type=sa.VARCHAR(length=255),
                    comment='Токен для сброса пароля',
                    existing_nullable=True)
    op.alter_column('users', 'password_reset_expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время истечения токена сброса пароля',
                    existing_nullable=True)
    op.alter_column('users', 'last_login',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Последний вход в систему',
                    existing_nullable=True)
    op.alter_column('users', 'login_count',
                    existing_type=sa.INTEGER(),
                    comment='Количество входов в систему',
                    existing_nullable=False,
                    existing_server_default=sa.text('0'))
    op.alter_column('users', 'role_name',
                    existing_type=sa.VARCHAR(length=50),
                    comment='Роль пользователя',
                    existing_nullable=False,
                    existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'id',
                    existing_type=sa.UUID(),
                    comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    comment='Время последнего обновления',
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_user_name_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_name'),
                    'users', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_user_name_key', 'users', ['user_name'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.alter_column('users', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    comment=None,
                    existing_comment='Время последнего обновления',
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('users', 'role_name',
                    existing_type=sa.VARCHAR(length=50),
                    comment=None,
                    existing_comment='Роль пользователя',
                    existing_nullable=False,
                    existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'login_count',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Количество входов в систему',
                    existing_nullable=False,
                    existing_server_default=sa.text('0'))
    op.alter_column('users', 'last_login',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Последний вход в систему',
                    existing_nullable=True)
    op.alter_column('users', 'password_reset_expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время истечения токена сброса пароля',
                    existing_nullable=True)
    op.alter_column('users', 'password_reset_token',
                    existing_type=sa.VARCHAR(length=255),
                    comment=None,
                    existing_comment='Токен для сброса пароля',
                    existing_nullable=True)
    op.alter_column('users', 'verification_expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время истечения токена верификации',
                    existing_nullable=True)
    op.alter_column('users', 'verification_token',
                    existing_type=sa.VARCHAR(length=255),
                    comment=None,
                    existing_comment='Токен для подтверждения email',
                    existing_nullable=True)
    op.alter_column('users', 'email_verified',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Подтвержден ли email',
                    existing_nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('users', 'bio',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Биография пользователя',
                    existing_nullable=True)
    op.alter_column('users', 'full_name',
                    existing_type=sa.VARCHAR(length=100),
                    comment=None,
                    existing_comment='Полное имя',
                    existing_nullable=True)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    comment=None,
                    existing_comment='Хешированный пароль',
                    existing_nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=100),
                    comment=None,
                    existing_comment='Email пользователя',
                    existing_nullable=False)
    op.alter_column('users', 'user_name',
                    existing_type=sa.VARCHAR(length=50),
                    comment=None,
                    existing_comment='Имя пользователя',
                    existing_nullable=False)
    op.drop_index(op.f('ix_refreshtokens_token'), table_name='refreshtokens')
    op.create_unique_constraint(
        'refreshtokens_token_key', 'refreshtokens', ['token'])
    op.alter_column('refreshtokens', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.alter_column('refreshtokens', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    comment=None,
                    existing_comment='Время последнего обновления')
    op.alter_column('refreshtokens', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('refreshtokens', 'id',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'expires_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время истечения',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'is_revoked',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Флаг отзыва токена',
                    existing_nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('refreshtokens', 'token',
                    existing_type=sa.VARCHAR(length=255),
                    comment=None,
                    existing_comment='Значение токена',
                    existing_nullable=False)
    op.alter_column('refreshtokens', 'user_id',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='ID пользователя',
                    existing_nullable=False)
    op.drop_index(op.f('ix_loginattempts_user_id'), table_name='loginattempts')
    op.alter_column('loginattempts', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Флаг активности записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('true'))
    op.alter_column('loginattempts', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    comment=None,
                    existing_comment='Время последнего обновления')
    op.alter_column('loginattempts', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    comment=None,
                    existing_comment='Время создания записи',
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('loginattempts', 'id',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='Уникальный идентификатор',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'failure_reason',
                    existing_type=sa.VARCHAR(length=100),
                    comment=None,
                    existing_comment='Причина неудачи',
                    existing_nullable=True)
    op.alter_column('loginattempts', 'is_successful',
                    existing_type=sa.BOOLEAN(),
                    comment=None,
                    existing_comment='Успешна ли попытка входа',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'user_agent',
                    existing_type=sa.VARCHAR(length=500),
                    comment=None,
                    existing_comment='User Agent браузера',
                    existing_nullable=True)
    op.alter_column('loginattempts', 'ip_address',
                    existing_type=sa.VARCHAR(length=45),
                    comment=None,
                    existing_comment='IP адрес, с которого была попытка',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'email',
                    existing_type=sa.VARCHAR(length=100),
                    comment=None,
                    existing_comment='Email, с которого была попытка входа',
                    existing_nullable=False)
    op.alter_column('loginattempts', 'user_id',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='ID пользователя (если пользователь существует)',
                    existing_nullable=True)
    # ### end Alembic commands ###
