"""create new table

Revision ID: bccd8ae6df97
Revises: 
Create Date: 2026-03-30 14:15:47.472852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccd8ae6df97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_name', sa.String(length=50),
                              nullable=False, comment='Имя пользователя'),
                    sa.Column('email', sa.String(length=100),
                              nullable=False, comment='Email пользователя'),
                    sa.Column('hashed_password', sa.String(length=255),
                              nullable=False, comment='Хешированный пароль'),
                    sa.Column('full_name', sa.String(length=100),
                              nullable=True, comment='Полное имя'),
                    sa.Column('bio', sa.Text(), nullable=True,
                              comment='Биография пользователя'),
                    sa.Column('email_verified', sa.Boolean(), nullable=False,
                              comment='Подтвержден ли email'),
                    sa.Column('verification_token', sa.String(length=255),
                              nullable=True, comment='Токен для подтверждения email'),
                    sa.Column('verification_expires_at', sa.DateTime(timezone=True),
                              nullable=True, comment='Время истечения токена верификации'),
                    sa.Column('password_reset_token', sa.String(length=255),
                              nullable=True, comment='Токен для сброса пароля'),
                    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True),
                              nullable=True, comment='Время истечения токена сброса пароля'),
                    sa.Column('last_login', sa.DateTime(timezone=True),
                              nullable=True, comment='Последний вход в систему'),
                    sa.Column('login_count', sa.Integer(), nullable=False,
                              comment='Количество входов в систему'),
                    sa.Column('role_name', sa.String(length=50),
                              nullable=False, comment='Роль пользователя'),
                    sa.Column('id', backend.shared.models.base.decorator.type_decorator.UUIDTypeDecorator(
                    ), nullable=False, comment='Уникальный идентификатор'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=False, comment='Время создания записи'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=True, comment='Время последнего обновления'),
                    sa.Column('is_active', sa.Boolean(), nullable=False,
                              comment='Флаг активности записи'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_name'), 'users',
                    ['role_name'], unique=False)
    op.create_index(op.f('ix_users_user_name'),
                    'users', ['user_name'], unique=True)
    op.create_table('loginattempts',
                    sa.Column('user_id', backend.shared.models.base.decorator.type_decorator.UUIDTypeDecorator(
                    ), nullable=True, comment='ID пользователя (если пользователь существует)'),
                    sa.Column('email', sa.String(length=100), nullable=False,
                              comment='Email, с которого была попытка входа'),
                    sa.Column('ip_address', sa.String(length=45), nullable=False,
                              comment='IP адрес, с которого была попытка'),
                    sa.Column('user_agent', sa.String(length=500),
                              nullable=True, comment='User Agent браузера'),
                    sa.Column('is_successful', sa.Boolean(), nullable=False,
                              comment='Успешна ли попытка входа'),
                    sa.Column('failure_reason', sa.String(length=100),
                              nullable=True, comment='Причина неудачи'),
                    sa.Column('id', backend.shared.models.base.decorator.type_decorator.UUIDTypeDecorator(
                    ), nullable=False, comment='Уникальный идентификатор'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=False, comment='Время создания записи'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=True, comment='Время последнего обновления'),
                    sa.Column('is_active', sa.Boolean(), nullable=False,
                              comment='Флаг активности записи'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_loginattempts_email'),
                    'loginattempts', ['email'], unique=False)
    op.create_index(op.f('ix_loginattempts_id'),
                    'loginattempts', ['id'], unique=False)
    op.create_index(op.f('ix_loginattempts_user_id'),
                    'loginattempts', ['user_id'], unique=False)
    op.create_table('refreshtokens',
                    sa.Column('user_id', backend.shared.models.base.decorator.type_decorator.UUIDTypeDecorator(
                    ), nullable=False, comment='ID пользователя'),
                    sa.Column('token', sa.String(length=255),
                              nullable=False, comment='Значение токена'),
                    sa.Column('is_revoked', sa.Boolean(), nullable=False,
                              comment='Флаг отзыва токена'),
                    sa.Column('expires_at', sa.DateTime(timezone=True),
                              nullable=False, comment='Время истечения'),
                    sa.Column('id', backend.shared.models.base.decorator.type_decorator.UUIDTypeDecorator(
                    ), nullable=False, comment='Уникальный идентификатор'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=False, comment='Время создания записи'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(
                        "timezone('utc', now())"), nullable=True, comment='Время последнего обновления'),
                    sa.Column('is_active', sa.Boolean(), nullable=False,
                              comment='Флаг активности записи'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_refreshtokens_id'),
                    'refreshtokens', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_token'),
                    'refreshtokens', ['token'], unique=True)
    op.create_index(op.f('ix_refreshtokens_user_id'),
                    'refreshtokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_user_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_token'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    op.drop_index(op.f('ix_loginattempts_user_id'), table_name='loginattempts')
    op.drop_index(op.f('ix_loginattempts_id'), table_name='loginattempts')
    op.drop_index(op.f('ix_loginattempts_email'), table_name='loginattempts')
    op.drop_table('loginattempts')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_role_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
