"""add ingredients table

Revision ID: c032a56e3537
Revises: b12345678901
Create Date: 2026-03-17 22:22:09.980277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c032a56e3537'
down_revision: Union[str, Sequence[str], None] = 'b12345678901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipes',
        sa.Column(
            'user_id',
            sa.UUID(),
            nullable=True,
            comment='ID пользователя (если пользователь существует)'
        ),
        sa.Column(
            'name_recipe',
            sa.String(length=50),
            nullable=False,
            comment='Название рецепта'
        ),
        sa.Column(
            'description',
            sa.String(length=50),
            nullable=False,
            comment='Описание рецепта'
        ),
        sa.Column(
            'id',
            sa.UUID(),
            nullable=False,
            comment='Уникальный идентификатор'
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
            comment='Время создания записи'
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
            comment='Время последнего обновления'
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            comment='Флаг активности записи'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_recipes_id'),
        'recipes',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_recipes_user_id'),
        'recipes',
        ['user_id'],
        unique=False
    )
    op.alter_column(
        'loginattempts',
        'user_id',
        existing_type=sa.UUID(),
        comment='ID пользователя (если пользователь существует)',
        existing_comment='ID пользователя',
        existing_nullable=True
    )
    op.alter_column(
        'loginattempts',
        'ip_address',
        existing_type=sa.VARCHAR(length=45),
        comment='IP адрес, с которого была попытка',
        existing_comment='IP адрес',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'is_successful',
        existing_type=sa.BOOLEAN(),
        comment='Успешна ли попытка входа',
        existing_comment='Успешна ли попытка',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время создания записи',
        existing_comment='Время создания',
        existing_nullable=False,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'loginattempts',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время последнего обновления',
        existing_comment='Время обновления',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'loginattempts',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Флаг активности записи',
        existing_comment='Активна ли запись',
        existing_nullable=False
    )
    op.alter_column(
        'refreshtokens',
        'is_revoked',
        existing_type=sa.BOOLEAN(),
        comment='Флаг отзыва токена',
        existing_comment='Отозван ли токен',
        existing_nullable=False
    )
    op.alter_column(
        'refreshtokens',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время создания записи',
        existing_comment='Время создания',
        existing_nullable=False,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'refreshtokens',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время последнего обновления',
        existing_comment='Время обновления',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'refreshtokens',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Флаг активности записи',
        existing_comment='Активна ли запись',
        existing_nullable=False
    )
    op.alter_column(
        'users',
        'role_name',
        existing_type=sa.VARCHAR(length=50),
        comment='Роль пользователя',
        existing_comment='Роль пользователя (user, moderator, admin)',
        existing_nullable=False,
        existing_server_default=sa.text("'user'::character varying")
    )
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Флаг активности записи',
        existing_comment='Активна ли запись',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Активна ли запись',
        existing_comment='Флаг активности записи',
        existing_nullable=False
    )
    op.alter_column(
        'users',
        'role_name',
        existing_type=sa.VARCHAR(length=50),
        comment='Роль пользователя (user, moderator, admin)',
        existing_comment='Роль пользователя',
        existing_nullable=False,
        existing_server_default=sa.text("'user'::character varying")
    )
    op.alter_column(
        'refreshtokens',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Активна ли запись',
        existing_comment='Флаг активности записи',
        existing_nullable=False
    )
    op.alter_column(
        'refreshtokens',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время обновления',
        existing_comment='Время последнего обновления',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'refreshtokens',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время создания',
        existing_comment='Время создания записи',
        existing_nullable=False,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'refreshtokens',
        'is_revoked',
        existing_type=sa.BOOLEAN(),
        comment='Отозван ли токен',
        existing_comment='Флаг отзыва токена',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'is_active',
        existing_type=sa.BOOLEAN(),
        comment='Активна ли запись',
        existing_comment='Флаг активности записи',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время обновления',
        existing_comment='Время последнего обновления',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'loginattempts',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='Время создания',
        existing_comment='Время создания записи',
        existing_nullable=False,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'loginattempts',
        'is_successful',
        existing_type=sa.BOOLEAN(),
        comment='Успешна ли попытка',
        existing_comment='Успешна ли попытка входа',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'ip_address',
        existing_type=sa.VARCHAR(length=45),
        comment='IP адрес',
        existing_comment='IP адрес, с которого была попытка',
        existing_nullable=False
    )
    op.alter_column(
        'loginattempts',
        'user_id',
        existing_type=sa.UUID(),
        comment='ID пользователя',
        existing_comment='ID пользователя (если пользователь существует)',
        existing_nullable=True
    )
    op.drop_index(
        op.f('ix_recipes_user_id'),
        table_name='recipes'
    )
    op.drop_index(
        op.f('ix_recipes_id'),
        table_name='recipes'
    )
    op.drop_table('recipes')
    # ### end Alembic commands ###
