# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from backend.shared.proto import user_service_pb2 as user__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """
    Сервис
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateToken = channel.unary_unary(
            '/user.UserService/ValidateToken',
            request_serializer=user__service__pb2.ValidateTokenRequest.SerializeToString,
            response_deserializer=user__service__pb2.ValidateTokenResponse.FromString,
            _registered_method=True)
        self.GetUserById = channel.unary_unary(
            '/user.UserService/GetUserById',
            request_serializer=user__service__pb2.GetUserByIdRequest.SerializeToString,
            response_deserializer=user__service__pb2.GetUserByIdResponse.FromString,
            _registered_method=True)


class UserServiceServicer(object):
    """
    Сервис
    """

    def ValidateToken(self, request, context):
        """Валидация JWT токена
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Получить пользователя по ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ValidateToken': grpc.unary_unary_rpc_method_handler(
            servicer.ValidateToken,
            request_deserializer=user__service__pb2.ValidateTokenRequest.FromString,
            response_serializer=user__service__pb2.ValidateTokenResponse.SerializeToString,
        ),
        'GetUserById': grpc.unary_unary_rpc_method_handler(
            servicer.GetUserById,
            request_deserializer=user__service__pb2.GetUserByIdRequest.FromString,
            response_serializer=user__service__pb2.GetUserByIdResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'user.UserService', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class UserService(object):
    """
    Сервис
    """

    @staticmethod
    def ValidateToken(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/ValidateToken',
            user__service__pb2.ValidateTokenRequest.SerializeToString,
            user__service__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/GetUserById',
            user__service__pb2.GetUserByIdRequest.SerializeToString,
            user__service__pb2.GetUserByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
